version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
