stages:
  - test

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

node:14:
  image: node:14
  stage: test
  before_script:
    - yarn
  script:
    - yarn test

node:16:
  image: node:16
  stage: test
  before_script:
    - yarn
  script:
    - yarn test
