stages:
  - test

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

node:10.15:
  image: node:10.15
  stage: test
  before_script:
    - npm ci
  script:
    - npm test

node:8.15:
  image: node:8.15
  stage: test
  before_script:
    - npm ci
  script:
    - npm test
