stages:
  - test

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

node:10:
  image: node:10
  stage: test
  before_script:
    - npm -g install npm@latest
    - npm ci
  script:
    - npm test

node:12:
  image: node:12
  stage: test
  before_script:
    - npm -g install npm@latest
    - npm ci
  script:
    - npm test
